# Generated by Django 4.2.4 on 2023-11-22 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
