# Generated by Django 4.2.4 on 2023-11-22 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0002_delete_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='condicionFinal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UTN.condicionfinal'),
        ),
    ]
