# Generated by Django 4.2.4 on 2023-11-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0003_condicionfinal_alter_inscripcion_condicionfinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='apellido',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profesor',
            name='correo',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(default='', max_length=255),
        ),
    ]
