# Generated by Django 4.2.4 on 2023-11-22 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0006_historial_inscripcion_notaevaluacion_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='UTN.usuario'),
        ),
    ]
