# Generated by Django 4.2.4 on 2023-11-23 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0009_alter_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipodocumento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UTN.tipodocumento'),
        ),
    ]
