# Generated by Django 4.2.7 on 2023-11-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0010_alter_usuario_documento_alter_usuario_tipodocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('asignatura', models.CharField(max_length=50)),
            ],
        ),
    ]
