# Generated by Django 4.2.4 on 2023-11-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0010_alter_usuario_documento_alter_usuario_tipodocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='carrera',
            field=models.ManyToManyField(null=True, to='UTN.carrera'),
        ),
    ]
