# Generated by Django 4.2.4 on 2023-11-24 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0011_usuario_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='materia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='UTN.materia'),
        ),
    ]
