# Generated by Django 4.2.4 on 2023-11-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0012_curso_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='carrera',
            field=models.ManyToManyField(default='', null=True, to='UTN.carrera'),
        ),
    ]
