# Generated by Django 4.2.4 on 2023-11-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0013_alter_usuario_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='fechaFinal',
            field=models.DateTimeField(null=True),
        ),
    ]
